---
- hosts: spotify
  remote_user: root
  tasks:
  - name: Add an apt key by id from a keyserver
    apt_key:
     keyserver: keyserver.ubuntu.com
     id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
  - apt_repository:
     repo: deb http://repository.spotify.com stable non-free
     state: present
     update_cache: yes
  - name: Install package "spotify-client"
    apt: 
     name: spotify-client

